### ISSUE TITLE
`asyncFirst`, don't cancel 

### ISSUE THREAD

**Issue by AndrewSB** [inamiy/FunAsync#13]
hey yasuhiro 😄 

quick question, how would you use `asyncFirst` in the case where you don't want to cancel the slower functions? as as illustrative example:

```swift
func getAPIModel() async throws -> APIModel {
  try await asyncFirst([
    { try await self.fetchFromCache(for: id) },
    {
        let fromAPI = try await self.fetchFromAPI(for: id)
        await self.setCached(id, fromAPI)
    },
  ])()
}
```

even if the first function to fetch from the cache succeeds, i don't want to cancel the second function, i still want to update the cache from the API request.

maybe async isn't the best way to compose this problem, and this is better suited to a Publisher that first gives the cached value if it exists, then the object from the API?

**Comment by inamiy** [comment]
Hi Andrew! Sorry for a late reply 😅

Your question is an interesting one.
I believe [`func asyncStream`](https://github.com/inamiy/FunAsync/blob/feb4f8142b6c097cb70410e88e5421a01648b247/Sources/FunAsync/AsyncStream.swift#L46) will combine 2 asyncs and runs in parallel, and you can grab the first value by `stream.first()` while this stream keeps running. 

Also, you might want to check https://github.com/apple/swift-async-algorithms/issues/109 `Task.select` too which also solves your problem while it requires `Task`s instead of async functions.
(But in the link, I'm actually proposing auto-cancellation of the other tasks which will be against your need 😝)

**Comment by AndrewSB** [comment]
thanks @inamiy not a problem at all!

i just wrote a test that validates that to prove it to myself. as always, thank you for your contribution to the functional swift community.
i might visit sometime next year, i'll message you when i know 😆
